spring:
  application:
    name: evaluador
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

app:
  cors:
    allowed-origins: http://localhost:5173
