spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=EvaluadorIA;encrypt=true;trustServerCertificate=true
    username: sa
    password: Evaluador#2026
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
